ItemList = {
    ['melee_lantern_electric'] = {
        type = 'weapon',
        name = 'Laterna Elétrica',
        weight = 1.0,
        description = 'Um pequeno lampião elétrico capaz de reproduzir luz através da eletricidade. Ótimo para ser usado em locais escuros.',
        stackSize = 1
    },
    ['melee_torch'] = {
        type = 'weapon',
        name = 'Tocha',
        weight = 1.0,
        description = 'Uma tocha feita do galho de uma árvore. Quando acesa, é útil para iluminar tudo ao seu redor.',
        stackSize = 1,
    },
    ['melee_broken_sword'] = {
        type = 'weapon',
        name = 'Espada Quebrada',
        weight = 1.0,
        description = 'A ruína de uma certa antiga espada ocidental, aparentemente está quebrada pela metade.',
        stackSize = 1,
    },
    ['fishingrod'] = {
        type = 'weapon',
        name = 'Vara de Pescar',
        weight = 1.0,
        description = 'Um pequeno cabo engatado por um grosso cipó e um gancho pequeno em sua ponta. Útil para pescas.',
        stackSize = 1,
    },
    ['melee_hatchet'] = {
        type = 'weapon',
        name = 'Machado',
        weight = 1.0,
        description = 'Um afiado machado de metal, além de servir como arma, é também perfeito para derrubar árvores!',
        stackSize = 1,
    },
    ['melee_cleaver'] = {
        type = 'weapon',
        name = 'Machado Cutelo',
        weight = 1.5,
        description = 'Aqui eis um antigo cutelo, estranhamento afiado, curiosamente ensanguentado.',
        stackSize = 1,
    },
    ['melee_ancient_hatchet'] = {
        type = 'weapon',
        name = 'Machado Raro',
        weight = 1.0,
        description = 'Ooooh... tão deslumbrante e brilhante, seria este o machado perfeito?',
        stackSize = 1,
    },
    ['melee_hatchet_viking'] = {
        type = 'weapon',
        name = 'Machado Viking',
        weight = 1.2,
        description = 'Coberto por um longo couro em seu cabo, esse machado vem de eras frias, tempos vikings, poucos colecionadores o possuem.',
        stackSize = 1,
    },
    ['melee_hatchet_hewing'] = {
        type = 'weapon',
        name = 'Machado Hewing',
        weight = 1.2,
        description = 'Este artefato pertenceu a família Hewing, que espetáculo.',
        stackSize = 1,
    },
    ['melee_hatchet_double_bit'] = {
        type = 'weapon',
        name = 'Machadinhas Duplas',
        weight = 1.9,
         description = 'Duas machadinhas, pequenas, mas rápidas e loucas pelo sangue de sua próxima vítima.',
        stackSize = 1,
    },
    ['melee_hatchet_double_bit_rusted'] = {
        type = 'weapon',
        name = 'Machadinhas Duplas Enferrujadas',
        weight = 2.0,
         description = 'Duas machadinhas, pequenas, mas rápidas, enferrujadas e loucas pelo sangue de sua próxima vítima.',
        stackSize = 1,
    },
    ['melee_hatchet_hunter'] = {
        type = 'weapon',
        name = 'Machado de Caçador',
        weight = 1.5,
        description = 'Se você tem esse machado, você certamente é um expert caçador.',
        stackSize = 1,
    },
    ['melee_hatchet_hunter_rusted'] = {
        type = 'weapon',
        name = 'Machado de Caçador Velho',
        weight = 1.5,
        description = 'Se você tem esse machado, você certamente é um expert caçador.',
        stackSize = 1,
    },
    ['melee_knife_jawbone'] = {
        type = 'weapon',
        name = 'Faca Jawbone',
        weight = 0.5,
        description = 'Essa faca pertenceu a uma grande família pizzaiola do norte, se prestar a atenção, verá que ele ainda tem cheiro de mussarela.',
        stackSize = 1,
    },
    ['melee_knife_hunter'] = {
        type = 'weapon',
        name = 'Faca de Caçador',
        weight = 0.5,
        description = 'Faca para caça.',
        stackSize = 1,
    },
    ['melee_knife_miner'] = {
        type = 'weapon',
        name = 'Faca Minerio',
        weight = 1.0,
        description = 'Faca forjada especialmente para cortar minérios.',
        stackSize = 1,
    },
    ['melee_knife_civil_war'] = {
        type = 'weapon',
        name = 'Faca de Guerra',
        weight = 1.0,
        description = 'Uma antiga faca, usada na época da guerra de Rhodes, o confronto entre os Braithwaites e os Gray.',
        stackSize = 1,
    },
    ['melee_knife_vampire'] = {
        type = 'weapon',
        name = 'Faca de Vampiro',
        weight = 1.5,
        description = 'Perfeitamente retilínea, assustadoramente oblíqua. Que segredos sobrenaturais esta faca esconde?',
        stackSize = 1,
    },
    ['melee_machete'] = {
        type = 'weapon',
        name = 'Peixeira',
        weight = 1.0,
        description = 'Trata-se de uma ferramenta muito comprida e afiada, ideal para partir peixes.',
        stackSize = 1,
    },
    ['thrown_tomahawk'] = {
        type = 'weapon',
        name = 'Machado Craftado',
        weight = 1.0,
        description = 'Um machado produzido com barra de metal, cipó e madeira. Parece resistente!',
        stackSize = 1,
    },
    ['thrown_tomahawk_ancient'] = {
        type = 'weapon',
        name = 'Machado Craftado Velho',
        weight = 1.0,
        description = 'Um machado produzido com barra de metal, cipó e madeira. Parece resistente, mas está velho.',
        stackSize = 1,
    },    
    ['thrown_throwing_knives'] = {
        type = 'weapon',
        name = 'Faca Arremessável',
        weight = 0.6,
        description = 'Uma pequena faca capaz de ser arremessada. Cuidado, é perfurante!',
        stackSize = 6,
    },
    ['melee_knife_john'] = {
        type = 'weapon',
        name = 'Faca do John',
        weight = 1.0,
        description = 'Esta faca pertenceu a John Marston, membro da gangue The Van der Linde.',
        stackSize = 1,
    },
    ['melee_knife'] = {
        type = 'weapon',
        name = 'Faca de Caça',
        weight = 1.0,
        description = 'Faca útil para esfolar animais, excelente na caçada.',
        stackSize = 1,
    },
    ['melee_knife_bear'] = {
        type = 'weapon',
        name = 'Faca de U,rso',
        weight = 1.0,
        description = 'Coitado do urso que serviu como vítima para a criação deste artefato.',
        stackSize = 1,
    },
    ['lasso'] = {
        type = 'weapon',
        name = 'Laço',
        weight = 0.7,
        description = 'Meu vaqueiro, meu peão, esse laço vai roubar seu coração!',
        stackSize = 1,
    },
    ['pistol_mauser'] = {
        type = 'weapon',
        name = 'Pistola Mauser',
        weight = 1.2,
        description = 'Pistola de alta durabilidade, útil em combate rápido.',
        stackSize = 1,
    },  
    ['pistol_mauser_drunk'] = {
        type = 'weapon',
        name = 'Pistola Mauser dos Braithwaites',
        weight = 1.4,
        description = 'Pistola herdada pela família Bronte, furtada por Mama na sua lua-de-mel com Pappa Bronte em fevereiro de 1896, após a queda dos Braithwaite.',
        stackSize = 1,
    },          
    ['pistol_m1899'] = {
        type = 'weapon',
        name = 'Pistola M1899',
        weight = 1.2,
        description = 'Eis aqui o futuro em suas mãos, uma pistola tecnologicamente inovadora.',
        stackSize = 1,
    },    
    ['pistol_semiauto'] = {
        type = 'weapon',
        name = 'Pistola Semi-auto',
        weight = 1.2,
        description = 'Pistola semi-automática, capaz de disparar uma boa quantia de balas em poucos segundos.',
        stackSize = 1,
    },
    ['pistol_volcanic'] = {
        type = 'weapon',
        name = 'Pistola Volcanic',
        weight = 1.2,
        description = 'Esta Pistola foi uma das mais utilizadas na guerra civil de Lemoyne, sua precisão e dano é inigualável.',
        stackSize = 5,
    },
    ['repeater_carbine'] = {
        type = 'weapon',
        name = 'Carabina de Repetição',
        weight = 2.0,
        description = 'Carabina capaz de disparar vários tiros em poucos segundos, sua recarga é fácil e rápida.',
        stackSize = 5,
    },
    ['repeater_henry'] = {
        type = 'weapon',
        name = 'Litchfield de Repetição',
        weight = 2.0,
        description = 'Rifle longo de repetição, precisamente letal e lépida.',
        stackSize = 1,
    },
    ['repeater_evans'] = {
        type = 'weapon',
        name = 'Evans de Repetição',
        weight = 2.0,
        description = 'Rifle longo de repetição, precisamente letal e lépido.',
        stackSize = 1,
    },
    ['repeater_winchester'] = {
        type = 'weapon',
        name = 'Winchester',
        weight = 2.0,
        description = 'Rifle longo de repetição, precisamente letal.',
        stackSize = 1,
    },
    ['rifle_varmint'] = {
        type = 'weapon',
        name = 'Rifle Anti-pragas',
        weight = 1.5,
        description = 'Rifle feito especialmente para caças, acertar uma bala de anti-pragas na cabeça de qualquer animal não-lendário certamente o matará.',
        stackSize = 1,
    },
    ['shotgun_repeating'] = {
        type = 'weapon',
        name = 'Winchester de Repetição',
        weight = 2.0,
        description = 'Rifle longo de repetição, ágil e letal.',
        stackSize = 1,
    },
    ['revolver_cattleman'] = {
        type = 'weapon',
        name = 'Revolver de Vaqueiro',
        weight = 1.2,
        description = 'Revólver simples e de porte livre, todos os peões possuem um.',
        stackSize = 1,
    },
    ['revolver_cattleman_john'] = {
        type = 'weapon',
        name = 'Revolver do John',
        weight = 1.2,
        description = 'Este revólver já esteve nas mãos de John Marston.',
        stackSize = 1,
    },
    ['revolver_cattleman_mexican'] = {
        type = 'weapon',
        name = 'Revolver Mexicano',
        weight = 1.2,
        description = 'Revólver de origem mexicana.',
        stackSize = 1,
    },
    ['revolver_cattleman_pig'] = {
        type = 'weapon',
        name = 'Revolver Granger',
        weight = 1.2,
        description = 'Este revólver pertenceu a família Aberdeen.',
        stackSize = 1,
    },    
    ['revolver_doubleaction'] = {
        type = 'weapon',
        name = 'Revolver Ação dupla',
        weight = 1.2,
        description = 'Este revólver é capaz de disparar duas balas em menos de um segundo, outrora, sua recarga requer um pouco mais de tempo.',
        stackSize = 1,
    },
    ['revolver_doubleaction_exotic'] = {
        type = 'weapon',
        name = 'Revolver Ação Dupla Raro',
        weight = 1.2,
        description = 'Revólver um tanto quanto raro... um tesouro!',
        stackSize = 1,
    },
    ['revolver_doubleaction_micah'] = {
        type = 'weapon',
        name = 'Revolver Ação Dupla Micah',
        weight = 1.2,
        description = 'Este revólver pertenceu a Micah Belle.',
        stackSize = 1,
    },
    ['revolver_lemat'] = {
        type = 'weapon',
        name = 'Revolver Lemat',
        weight = 1.2,
        description = 'O revólver Lemat causa um dano desestrutural a inimigos alados, seja rápido e sua presa não resistirá.',
        stackSize = 1,
    },
    -- ['revolver_navy'] = {
    --     type = 'weapon',
    --     name = 'Revolver da Marinha',
    --     weight = 1.2,
    --     description = 'Este revólver é exclusivo da marinha de Saint Denis.',
    --     stackSize = 1,
    -- },
    ['revolver_schofield'] = {
        type = 'weapon',
        name = 'Revolver Schofield',
        weight = 1.2,
        description = 'O Schofield é um revólver com seis disparos, útil em combate a menos de 8 metros.',
        stackSize = 1,
    },    
    ['revolver_schofield_golden'] = {
        type = 'weapon',
        name = 'Revolver Schofield Gold',
        weight = 2.0,
        description = 'Revólver de prestígio dos ricos.',
        stackSize = 1,
    },
    ['revolver_schofield_calloway'] = {
        type = 'weapon',
        name = 'Revolver Schofield Calloway',
        weight = 2.0,
        description = 'Este revólver pertenceu a Jim Boy Calloway.',
        stackSize = 1,
    },    
    ['rifle_boltaction'] = {
        type = 'weapon',
        name = 'Rifle de Ferrolho',
        weight = 2.5,
        description = 'Rifle feito de barras de metal ligeiramente impecáveis, a bala atravessa o cano de maneira lépida e consegue atravessar qualquer ponto sólido.',
        stackSize = 1,
    },    
    ['sniperrifle_carcano'] = {
        type = 'weapon',
        name = 'Rifle Carcano',
        weight = 4.5,
        description = 'Um rifle capaz de executar disparos a longa distância. Sua cadência é boa, mas os tiros requerem precisão.',
        stackSize = 1,
    },
    ['sniperrifle_rollingblock'] = {
        type = 'weapon',
        name = 'Rifle Rolling Block',
        weight = 4.5,
        description = 'Um rifle capaz de executar disparos a longa distância. Uma bala já é o bastante para matar qualquer inimigo.',
        stackSize = 1,
    },
    ['sniperrifle_rollingblock_exotic'] = {
        type = 'weapon',
        name = 'Rifle Rolling Block Raro',
        weight = 4.5,
        description = 'Um rifle capaz de executar disparos a longa distância. Uma bala já é o bastante para matar qualquer inimigo. É rara.',
        stackSize = 1,
    },
    ['rifle_springfield'] = {
        type = 'weapon',
        name = 'Rifle Springfield',
        weight = 2.5,
        description = 'Um rifle capaz de executar disparos a longa distância.',
        stackSize = 1,
    },
    ['shotgun_doublebarrel'] = {
        type = 'weapon',
        name = 'Escopeta de Cano duplo',
        weight = 2.2,
        description = 'Pequena arma que possui uma cadência de disparo implacável.',
        stackSize = 1,
    },
    ['shotgun_doublebarrel'] = {
        type = 'weapon',
        name = 'Escopeta de Cano duplo Raro',
        weight = 2.5,
        description = 'Pequena arma que possui uma cadência de disparo implacável, capaz de arrancar a cabeça de quaisquer pessoas. É rara.',
        stackSize = 1,
    },
    ['shotgun_double_pump'] = {
        type = 'weapon',
        name = 'Escopeta de Cano duplo Pump',
        weight = 2.2,
        description = 'Pequena arma que possui uma cadência de disparo implacável, capaz de arrancar a cabeça de quaisquer pessoas.',
        stackSize = 1,
    },
    ['shotgun_pump'] = {
        type = 'weapon',
        name = 'Escopeta Pump-Action',
        weight = 2.2,
        description = 'Um armamento capaz de disparar vários projéteis perfurantes ao mesmo tempo.',
        stackSize = 1,
    },
    ['shotgun_repeating'] = {
        type = 'weapon',
        name = 'Escopeta Repetidora',
        weight = 2.2,
        description = 'Um armamento capaz de disparar vários projéteis ao mesmo tempo e de maneira repetitiva, lépida.',
        stackSize = 1,
    },
    ['shotgun_sawedoff'] = {
        type = 'weapon',
        name = 'Escopeta Cano serrado',
        weight = 2.2,
        description = 'Um armamento capaz de disparar vários projéteis ao mesmo tempo.',
        stackSize = 1,
    },
    ['shotgun_semiauto'] = {
        type = 'weapon',
        name = 'Escopeta Semi Auto',
        weight = 2.2,
        description = 'Um armamento capaz de disparar vários projéteis ao mesmo tempo. É semi-automática.',
        stackSize = 1,
    },
    ['bow'] = {
        type = 'weapon',
        name = 'Arco',
        weight = 1.0,
        description = 'Palett dobradiça fundida à corda, quando equipado com uma flecha, é capaz de dispara-la a distâncias incomparáveis.',
        stackSize = 1,
    },
    -- ['thrown_dynamite'] = {
    --     type = 'weapon',
    --     name = 'Dinamite',
    --     weight = 0.3,
    --     description = 'Composto explosivo cheio de pólvora em seu interior, quando aceso o pavio, explode em 1,5s após a queima.',
    --     stackSize = 3,
    -- },
    ['thrown_molotov'] = {
        type = 'weapon',
        name = 'Molotov',
        weight = 0.3,
        description = 'Frasco enrijecido com moonshine, altamente inflamável quando aceso.',
        stackSize = 6,
    },
    -- ['bread'] = {
    --     type = 'food',
    --     name = 'Pão',
    --     weight = 0.1,
    --     varOnUse = 1.0,
    --     description = 'Alimento produzido através de massa e farinha.',
    --     stackSize = 5,
    -- },
    -- ['apple'] = {
    --     type = 'food',
    --     name = 'Maçã',
    --     weight = 0.3,
    --     description = 'Uma fruta recém colhida, serve de alimento para humanos e animais.',
    --     stackSize = 5,
    -- },
    -- ['carrot'] = {
    --     type = 'food',
    --     name = 'Cenoura',
    --     weight = 0.3,
    --     description = 'Um legume recém colhido, serve de alimento para humanos e animais.',
    --     stackSize = 5,
    -- },
     ---------------------------------------------
    ["tonic_health"] = {
        type = 'tonic',
        name = 'Tônico de Vida',
        weight = 0.4,
        varOnUse = 25,
        description = 'Tônico de Vida, ajuda na saúde. É um líquido medicinal.',
        stackSize = 1,
    },
    ["tonic_stamina"] = {
        type = 'tonic',
        name = 'Tônico de Energia',
        weight = 0.4,
        varOnUse = 25,
        description = 'Tônico de Energia, ajuda a melhorar a disposição física de seu corpo.',
        stackSize = 1,
    },
     ---------------------------------------------
    ["boost_health"] = {
        type = 'boost',
        name = 'Boost de Vida',
        description = 'Tônico de Vida, ajuda na saúde. É um líquido medicinal.',
        weight = 0.4,
        stackSize = 1,
    },
    ["boost_stamina"] = {
        type = 'boost',
        name = 'Boost de Energia',
        weight = 0.4,
        description = 'Tônico de Energia, ajuda a melhorar a disposição física de seu corpo.',
        stackSize = 1,
    },
    ---------------------------------------------
    ---------------------------------------------
    ["horse_boost_health"] = {
        type = 'boost',
        name = 'Boost de Vida para Cavalo',
        weight = 0.4,
        varOnUse = 25,
        description = 'Tônico de Vida, ajuda na saúde. É um líquido medicinal.',
        stackSize = 1,
    },
    ["horse_boost_stamina"] = {
        type = 'boost',
        name = 'Boost de Energia para Cavalo',
        weight = 0.4,
        varOnUse = 25,
        description = 'Tônico de Energia, ajuda a melhorar a disposição física de seu corpo.',
        stackSize = 1,
    },
     ---------------------------------------------
    ['ginseng_elixier'] = {
        type = 'beverage',
        name = 'Cerveja',
        weight = 0.7,
        varOnUse = 1.0,
        description = 'A cerveja é uma bebida produzida a partir da fermentação de cereais, principal bebida das festas.',
        stackSize = 10,
    },
    ['irish_whiskey'] = {
        type = 'beverage',
        name = 'Uísque',
        weight = 0.8,
        varOnUse = 1.0,
        description = 'Bebida alcólica, razoável, ajuda a relaxar.',
        stackSize = 8,
    },
    ['moonshine'] = {
        type = 'beverage',
        name = 'Moonshine',
        weight = 0.4,
        varOnUse = 1.0,
        description = 'Bebida alcólica destilada de alto teor, produzido através do mosto de milho. É ilícita.',
        stackSize = 25,
    },
    ['waterbottle'] = {
        type = 'beverage',
        name = 'Garrafa de Água',
        weight = 0.2,
        varOnUse = 1.0,
        description = 'Uma simples garrafa de plástico preenchida com água.',
        stackSize = 7,
    },
    ['meat'] = {
        type = 'generic',
        name = 'Carne Animal',
        weight = 1.0,
        description = 'Carne obtida após esfolar o animal',
        stackSize = 6,
    },
    ['raw_iron'] = {
        type = 'generic',
        name = 'Metal Bruto',
        weight = 4.2,
        description = 'Mineral pica',
        stackSize = 7,
    },
    ['raw_gold'] = {
        type = 'generic',
        name = 'Ouro Bruto',
        weight = 7.0,
        description = 'Ouro recém minerado, está em forma bruta, e por isso é tão pesado.',
        stackSize = 7,
    },
    ['raw_copper'] = {
        type = 'generic',
        name = 'Minério de Cobre',
        weight = 1.0,
        description = 'Uma pedra de cobre bem suja e danificada, pode ser processada para virar uma barra.',
        stackSize = 20,
    },
    ['raw_coal'] = {
        type = 'generic',
        name = 'Minério de Carvão',
        weight = 1.0,
        description = 'Carvão amontoado, precisa ser refinado para extrair seu sulfato inflamável.',
        stackSize = 45,
    },
    ['coal'] = {
        type = 'generic',
        name = 'Carvão Refinado',
        weight = 1.0,
        description = 'Minério de carvão já processado.',
        stackSize = 20,
    },
    ['log'] = {
        type = 'generic',
        name = 'Tora de Madeira',
        weight = 1.0,
        description = 'Toco de madeira, pobrezito, arrancado de suas raízes tão cedo.',
        stackSize = 20,
    },
    ['potassio'] = {
        type = 'generic',
        name = 'Nitrato de Potássio',
        weight = 1.0,
        description = 'Salitre é um nitrato de potássio usado para várias finalidades, como produzir fertilizantes e explosivos.',
        stackSize = 17,
    },
    ['sulfur'] = {
        type = 'generic',
        name = 'Enxofre',
        weight = 2.0,
        description = 'O sulfato de enxofre é removido das áreas termais de West Elizabeth, serve para a criação de pólvora.',
        stackSize = 10,
    },
    ['feather_1'] = {
        type = 'generic',
        name = 'Pluma de Garcinha-Branca',
        weight = 0.1,
        description = 'Pluma obtida apartir do depenamento de aves',
        stackSize = 1,
    },
    ['feather_2'] = {
        type = 'generic',
        name = 'Pluma de Garça-Vermelha',
        weight = 0.1,
        description = 'Pluma obtida apartir do depenamento de aves',
        stackSize = 1,
    },
    ['feather_3'] = {
        type = 'generic',
        name = 'Pluma de Garça-Branca-Pequena',
        weight = 0.1,
        description = 'Pluma obtida apartir do depenamento de aves',
        stackSize = 1,
    },
    ['feather_4'] = {
        type = 'generic',
        name = 'Pluma de Garça-Grande',
        weight = 0.1,
        description = 'Pluma obtida apartir do depenamento de aves',
        stackSize = 1,
    },
    ['feather_5'] = {
        type = 'generic',
        name = 'Pluma de Colhereiro-Americano',
        weight = 0.1,
        description = 'Pluma obtida apartir do depenamento de aves',
        stackSize = 1,
    },
    ['pigeonpost'] = {
        type = 'kit',
        name = 'Pombo-Correio',
        weight = 2.5,
        description = 'Entrega mensagems a longas distâncias',
        stackSize = 1,
    },
    ['tobacco_seed'] = {
        type = 'planting',
        name = 'Semente de Tabaco',
        weight = 0.2,
        description = 'Uma pequena lasca de uma semente nicotiana, pode ser plantada.',
        stackSize = 15,
    },
    ['sugarcane_seed'] = {
        type = 'planting',
        name = 'Semente de Cana',
        weight = 0.2,
        description = 'Uma pequena lasca de uma semente, pode ser plantada.',
        stackSize = 15,
    },
    ['corn_seed'] = {
        type = 'planting',
        name = 'Semente de Milho',
        weight = 0.2,
        description = 'Uma pequena lasca de uma semente, pode ser plantada.',
        stackSize = 15,
    },
    ['wateringcan'] = {
        type = 'planting',
        name = 'Balde de Água',
        weight = 1.5,
        description = 'Balde feito de barra de ferro, é bem resistente e está cheio de água.',
        stackSize = 7,
    },
    ['ammo_throwing_knives'] = {
        type = 'ammo',
        name = 'Facas Arremessáveis',
        weight = 0.1,
        description = 'Um pequeno conjunto de facas arremessáveis, podem ser recuperadas após o lançamento.',
        stackSize = 7,
    },
    ['ammo_pistol'] = {
        type = 'ammo',
        name = 'Munição de Pistola',
        weight = 0.1,
        description = 'Munição produzida especialmente para pistolas.',
        stackSize = 60,
    },
    -- ['ammo_pistol_express'] = {
    --     type = 'ammo',
    --     name = 'Munição de Pistola Expressa',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para pistolas do tipo split, letais.',
    --     stackSize = 60,
    -- },
    -- ['ammo_pistol_express_explosive'] = {
    --     type = 'ammo',
    --     name = 'Munição de Pistola Explosiva',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para pistolas do tipo split, conteúdo insanamente inflamável.',
    --     stackSize = 60,
    -- },
    -- ['ammo_pistol_high_velocity'] = {
    --     type = 'ammo',
    --     name = 'Munição de Pistola Rápida',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para pistolas do tipo split, rápidas e translúcidas.',
    --     stackSize = 60,
    -- },
    -- ['ammo_pistol_split_point'] = {
    --     type = 'ammo',
    --     name = 'Munição de Pistola Split',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para pistolas do tipo split.',
    --     stackSize = 60,
    -- },
    ['ammo_revolver'] = {
        type = 'ammo',
        name = 'Munição de Revolver',
        weight = 0.1,
        description = 'Munição produzida especialmente para revólveres.',
        stackSize = 60,
    },
    -- ['ammo_revolver_express'] = {
    --     type = 'ammo',
    --     name = 'Munição de Revolver Expresso',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para revólveres, bala translúcida e letal.',
    --     stackSize = 60,
    -- },
    -- ['ammo_revolver_express_explosive'] = {
    --     type = 'ammo',
    --     name = 'Munição de Revolver Explosivo',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para revólveres, bala encoberta por enxofre explosivo.',
    --     stackSize = 60,
    -- },
    -- ['ammo_revolver_high_velocity'] = {
    --     type = 'ammo',
    --     name = 'Munição de Revolver Rápida',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para revólveres, bala ágil e silenciosa.',
    --     stackSize = 60,
    -- },
    -- ['ammo_revolver_split_point'] = {
    --     type = 'ammo',
    --     name = 'Munição de Revolver Split',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para revólveres do tipo split.',
    --     stackSize = 60,
    -- },
    ['ammo_repeater'] = {
        type = 'ammo',
        name = 'Munição de Carabina',
        weight = 0.1,
        description = 'Munição produzida especialmente para carabinas.',
        stackSize = 45,
    },
    -- ['ammo_repeater_express'] = {
    --     type = 'ammo',
    --     name = 'Munição de Carabina Expressa',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para carabinas.',
    --     stackSize = 45,
    -- },
    -- ['ammo_repeater_express_explosive'] = {
    --     type = 'ammo',
    --     name = 'Munição de Carabina Explosiva',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para carabinas. É uma bala lenta, porém explosiva.',
    --     stackSize = 45,
    -- },
    -- ['ammo_repeater_high_velocity'] = {
    --     type = 'ammo',
    --     name = 'Munição de Carabina Rápida',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para carabinas. É uma bala rápida e perfurante.',
    --     stackSize = 45,
    -- },
    ['ammo_rifle'] = {
        type = 'ammo',
        name = 'Munição de Rifle',
        weight = 0.1,
        description = 'Munição produzida especialmente para rifles.',
        stackSize = 45,
    },
    -- ['ammo_rifle_express'] = {
    --     type = 'ammo',
    --     name = 'Munição de Rifle Expresso',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para rifles.',
    --     stackSize = 60,
    -- },
    -- ['ammo_rifle_express_explosive'] = {
    --     type = 'ammo',
    --     name = 'Munição de Rifle Explosiva',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para rifles. Está coberta por pólvora, inflama e eclode ao contato sólido.',
    --     stackSize = 60,
    -- },
    -- ['ammo_rifle_high_velocity'] = {
    --     type = 'ammo',
    --     name = 'Munição de Rifle Rápida',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para rifles. É uma bala lépida que causa maior perfuração ao seu alvo.',
    --     stackSize = 60,
    -- },
    -- ['ammo_rifle_split_point'] = {
    --     type = 'ammo',
    --     name = 'Munição de Rifle Split',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para rifles do tipo split.',
    --     stackSize = 60,
    -- },
    ['ammo_rifle_varmint'] = {
        type = 'ammo',
        name = 'Munição de Rifle',
        weight = 0.1,
        description = 'Munição produzida especialmente para rifles.',
        stackSize = 60,
    },
    ['ammo_shotgun'] = {
        type = 'ammo',
        name = 'Munição de Shotgun',
        weight = 0.1,
        description = 'Munição produzida especialmente para shotguns.',
        stackSize = 35,
    },
    -- ['ammo_shotgun_buckshot_incendiary'] = {
    --     type = 'ammo',
    --     name = 'Munição de Shotgun Incendiária',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para shotguns. É inflamável e incendeia ao contato.',
    --     stackSize = 35,
    -- },
    -- ['ammo_shotgun_express_explosive'] = {
    --     type = 'ammo',
    --     name = 'Munição de Shotgun Explosiva',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para shotguns. Explode ao contato.',
    --     stackSize = 35,
    -- },
    -- ['ammo_shotgun_slug'] = {
    --     type = 'ammo',
    --     name = 'Munição de Shotgun Slug',
    --     weight = 0.1,
    --     description = 'Munição produzida especialmente para shotguns.',
    --     stackSize = 35,
    -- },
    ['ammo_arrow'] = {
        type = 'ammo',
        name = 'Flecha',
        weight = 0.2,
        description = 'Munição produzida especialmente para arcos.',
        stackSize = 25,
    },
    -- ['ammo_arrow_dynamite'] = {
    --     type = 'ammo',
    --     name = 'Flecha Explosiva',
    --     weight = 0.2,
    --     description = 'Esta é uma flecha composta por um alto valor de pólvora inflamável, explode ao contato.',
    --     stackSize = 25,
    -- },
    -- ['ammo_arrow_fire'] = {
    --     type = 'ammo',
    --     name = 'Flecha Explosiva',
    --     weight = 0.2,
    --     description = 'Esta é uma flecha composta por um alto valor de pólvora inflamável, explode ao contato.',
    --     stackSize = 10,
    -- },
    -- ['ammo_arrow_improved'] = {
    --     type = 'ammo',
    --     name = 'Flecha Aprimorada',
    --     weight = 0.3,
    --     description = 'Flecha encoberta por uma linha de metal extremamente letal.',
    --     stackSize = 25,
    -- },    
    -- ['ammo_arrow_poison'] = {
    --     type = 'ammo',
    --     name = 'Flecha',
    --     weight = 0.2,
    --     description = 'Uma flecha venenosa.',
    --     stackSize = 25,
    -- },
    -- ['ammo_arrow_small_game'] = {
    --     type = 'ammo',
    --     name = 'Flecha',
    --     weight = 0.2,
    --     description = 'Munição produzida especialmente para arcos.',
    --     stackSize = 25,
    -- },
    ['tobacco'] = {
        type = 'generic',
        name = 'Tabaco',
        weight = 0.5,
        description = 'Produto extraído a partir de plantas nicotianas.',
        stackSize = 35,
    },
    ['corn'] = {
        type = 'generic',
        name = 'Milho',
        weight = 0.5,
        description = 'Um masto de cereal cultivado em terras férteis. Alimento humano e animal.',
        stackSize = 50,
    },
    ['sugar'] = {
        type = 'generic',
        name = 'Açúcar',
        weight = 0.5,
        description = 'Material extraído das canas-de-açucar de Rhodes, o açúcar é útil em várias criações.',
        stackSize = 45,
    },
    ['pickaxe'] = {
        type = 'generic',
        name = 'Picareta',
        weight = 1.5,
        description = 'Uma simples picareta de pedra, útil na mineração.',
        stackSize = 2,
    },
    ['potassio'] = {
        type = 'generic',
        name = 'Potassio',
        weight = 0.7,
        description = 'O potássio é um elemento extremamente violento quando em combustão, seu uso é diverso.',
        stackSize = 30,
    },
    ['sulfur'] = {
        type = 'generic',
        name = 'Enxofre',
        weight = 0.5,
        description = 'O sulfato de enxofre é removido das áreas termais de West Elizabeth, serve para a criação de pólvora.',
        stackSize = 30,
    },
    ['chest_small'] = {
        type = 'kit',
        name = 'Baú Pequeno',
        weight = 3.5,
        varOnUse = 25,
        description = 'Baú de madeira. É pequeno, mas cabe algumas coisas nele.',
        stackSize = 2,
    },
    ['chest_medium'] = {
        type = 'kit',
        name = 'Baú Médio',
        weight = 4.5,
        varOnUse = 50,
        description = 'Baú de madeira fortificado com peças de ferro. Serve para guardar alguns itens.',
        stackSize = 2,
    },
    ['chest_large'] = {
        type = 'kit',
        name = 'Baú Grande',
        weight = 5.0,
        varOnUse = 100,
        description = 'Baú de madeira fortificado com peças de metal. Serve para guardar grandes conteúdos.',
        stackSize = 2,
    },
    ['money'] = {
        type = 'valuable',
        name = 'Dólar',
        weight = 0.00001,
        description = 'Uma nota de valor, pode ser usada para comprar diversos itens. É a moeda da economia.',
        stackSize = -1,
    },
    ['gold'] = {
        type = 'valuable',
        name = 'Barra de Ouro',
        weight = 0.0007,
        description = 'Uma brilhante e cara barra de ouro.',
        stackSize = -1,
    },
    ['map'] = {
        type = 'document',
        name = 'Mapa da Cidade',
        weight = 0.007,
        description = 'Com este mapa você consegue visualizar todos os lugares da cidade.',
        stackSize = -1,
    },
    ['notepad'] = {
        type = 'document',
        name = 'Papel',
        weight = 0.007,
        description = 'Com este papel você consegue escrever anotações ou uma carta.',
        stackSize = -1,
    }
}
